/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sample_project;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.Iterator;

class AppTest {
    @Test void appHasAGreeting() {
        LinkedList<Integer> list = new LinkedList<Integer>();
        list.add(1);
        Iterator<Integer> iter = list.iterator();
        assert(iter.hasNext());
        assertNotNull(iter.next());
        assertFalse(iter.hasNext());

        boolean exceptionThrown = false;
        try {
            iter.next();
        } catch (Exception e) {
            exceptionThrown = true;
        }

        assertTrue(exceptionThrown);
    }
}
